#! /bin/bash

filename=$(basename $1)
ext=${filename##*.}

echo -n '<img src="'
if [ $ext == gif ]; then
    echo -n 'data:image/gif;base64,'
elif [ $ext == jpeg ] || [ $ext == jpg ]; then
    echo -n 'data:image/jpeg;base64,'
elif [ $ext == png ]; then
    echo -n 'data:image/png;base64,'
elif [ $ext == svg ]; then
    echo -n 'data:image/svg+xml;base64,'
elif [ $ext == ico ]; then
    echo -n 'data:image/vnd.microsoft.icon;base64,'
fi

#Mathias Bynens - http://superuser.com/questions/120796/os-x-base64-encode-via-command-line
#data=$(openssl base64 < $1 | tr -d '\n')

curl -s $1 | openssl base64 | tr -d '\n'

echo -n '"></img>'
