#!/bin/sh

. jjhfunctions

function usage(){
        echo "$1"
        die "Usage: $ME [path]"
}
DIR=$1

[ -z "$DIR" ] && DIR="`pwdms`"

[ -f "$DIR" ] && DIR="`dirname "$DIR"`"

DIR=`cygpath -wa "$DIR"`

explorer "$DIR"

