#!/bin/sh
. jjhfunctions

usage(){
        echo $1
        echo "Usage: $ME -P prog -s svr -d db -u uid -p pwd"
        exit 1
}

while getopts "P:u:p:d:s:" opt
do
    case "$opt" in
            P) PROG="$OPTARG";;
            u) UNAME="$OPTARG";;
            p) PASS="$OPTARG";;
            d) DB="$OPTARG";;
            s) SRV="$OPTARG";;
    esac
done

tmp=$DB; resolveprog; DB=$tmp

[ -z "$DB" ] && usage "missing -d"
[ -z "$SRV" ] && usage "missing -s"

sql="drop database $DB"
warn "$sql"
qry -u "$UNAME" -p "$PASS" -d master -s "$SRV" -q "$sql" >&2 
exit $?
