#!/bin/bash
. functions
WORD="$1"
LOGDIR=~/git/ts/var/log/sd
URL=http://dictionary.reference.com/browse
FILE="$LOGDIR/$WORD"

if test -e "$FILE" ; then
    echo "This word has already been sought... "
    read -n1 -p "`cat "$FILE"`"
    echo "Reviewed: `date`" >> "$FILE"
else
    read -p "Source: "
    if [ "x$REPLY" != 'xnvm' ]; then
        echo "Source: $REPLY" > "$FILE" 
        echo "First viewed: `date`" >> "$FILE"
        git add "$FILE"
        git commit -m"$ME: Adding $WORD" "$FILE"
        git push origin master
    fi
fi

links $URL/"$WORD" 

